language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - travis_retry npm ci
  - travis_retry gem install s3_website -v 3.1.0
script:
  - npm run lint:test && npm test
  - npm run start & wait-on http://localhost:8080
  - npm run test:cypress
  - 'CURRENT_TAG=`git describe --tags --exact-match $TRAVIS_COMMIT 2> /dev/null`;
     if [ "$TRAVIS_BRANCH" = "production" ] || [ "$TRAVIS_BRANCH" = "$CURRENT_TAG" ]; then
       npm run build-production;
     else
       npm run build;
     fi'
after_script:
  - deploy/s3_deploy.sh

addons:
  artifacts:
    paths:
      - ./cypress/screenshots
      - ./cypress/snapshots/snapshots.js/__diff_output__
    target_paths:
      - /tectonic-explorer/build-artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
